[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Scheduled function para enviar notifications
[[plugins]]
  package = "netlify-plugin-scheduled-functions"
  
  [plugins.inputs]
    [plugins.inputs.send-daily-love]
      schedule = "0 7 * * *"  # 7 AM todos los días